[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 10
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"

[es]
  languageName = "Español"
  contentDir = "content/es"
  weight = 1
  [de.params]
    languageISO = "ES"
    languageTag = "es-CL"
